### ISSUE TITLE
New release after updating Angular

### ISSUE THREAD

**Issue by RastoStric** [cloudnc/ngx-favicon#11]
Hello,

thanks for this library, it has saved me a great amount of time.

Correct me if I'm wrong but it seems that after updating Angular to 10 you have not published a new release. Now I am trying to update Angular in my project and it fails on ngx-favicon, because the latest version 1.1.0 still references Angular 7.

Could you please have a look at it?

Thank you

Rasto

**Comment by maxime1992** [comment]
Hi @RastoStric :wave: 

Thanks to @maroon17 we've got the upgrade! BUT! I just noticed that something probably went wrong on Travis as we merged it and nothing got released. I'll have a look asap :+1:

**Comment by maxime1992** [comment]
(also note that it doesn't seem to be an issue, we're using this lib on our app with angular 10 and everything is fine).

Are you encountering any issue on your side?

**Comment by RastoStric** [comment]
Thanks for such a quick response 👏. As far as I can tell the lib is working fine, I am currently on angular 9, I just needed to --force during the update. And I am glad to hear that I am not going to have an issue with it in angular 10 🙂
Thanks again.

**Comment by j3ronymo** [comment]
Hi @maxime1992 

I'd like to ask if you could tell me when will new release be available. Right now `npm i ngx-favicon` is installing version 1.1.0 which is 2 years old and building Angular10 app is returning error as such:
```sh
ERROR in node_modules/ngx-favicon/lib/ngx-favicon.module.d.ts:4:114 - error TS2314: Generic type 'ModuleWithProviders<T>' requires 1 type argument(s).

static forRoot<CustomFaviconConfig extends Dictionary<string>>(conf: NgxFaviconConfig<CustomFaviconConfig>): ModuleWithProviders;
```
I have looked at recent changes in [ngx-favicon.module.ts](https://github.com/cloudnc/ngx-favicon/blob/master/projects/ngx-favicon/src/lib/ngx-favicon.module.ts) and it looks like this issue was fixed.

Thank you.

**Comment by maxime1992** [comment]
I believe that has been fixed? Closing but let me know if you want me to reopen
